name: Sync S3 Files

on:
  push:
    branches:
      - main
    paths:
      - 's3-files/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Single sync command that maintains directory structure
      - name: Sync Files to S3
        run: |
          aws s3 sync s3-files/ s3://xaiproject.net/ --exclude ".git/*" --delete
