name: Sync S3 Files

on:
  push:
    branches:
      - main  # Run this action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials using GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change this to your region if different

      # Step 3: Sync the entire directory to S3, updating only changed files
      - name: Sync S3 Files
        run: |
          aws s3 sync CalculatorProject/s3-files/ s3://xaiproject.net/ --exclude ".git/*" --delete
