name: Deploy Lambda Functions

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials with a hardcoded region
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Specify your region

      # Step 3: Deploy only the relevant file for the CalculatorTest Lambda function
      - name: Deploy CalculatorTest Lambda function
        run: |
          cd lambda-functions/calculator  # Navigate to the correct directory
          zip ../calculator.zip calculator.py  # Zip only the calculator.py file
          aws lambda update-function-code \
            --function-name CalculatorTest \
            --zip-file fileb://../calculator.zip

      # Step 4: Deploy only the relevant file for the count_update_calculator Lambda function
      - name: Deploy count_update_calculator Lambda function
        run: |
          cd lambda-functions/count-update  # Navigate to the correct directory
          zip ../count_update.zip count_update.py  # Zip only the count_update.py file
          aws lambda update-function-code \
            --function-name count_update_calculator \
            --zip-file fileb://../count_update.zip

      # Step 5: Deploy only the relevant file for the UpdateWebsite Lambda function
      - name: Deploy UpdateWebsite Lambda function
        run: |
          cd lambda-functions/update-website  # Navigate to the correct directory
          zip ../update_website.zip update_website.py  # Zip only the update_website.py file
          aws lambda update-function-code \
            --function-name UpdateWebsite \
            --zip-file fileb://../update_website.zip

      # Optional: Debug environment variables
      - name: Debug Environment Variables
        run: env | sort
