name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials with a hardcoded region
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Using v2 instead of v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }} 

      # Step 3: Zip and deploy the CalculatorTest Lambda function
      - name: Deploy CalculatorTest Lambda function
        run: |
          zip -r calculator.zip .
          aws lambda update-function-code \
            --function-name CalculatorTest \
            --zip-file fileb://calculator.zip

      # Step 4: Zip and deploy the count_update_calculator Lambda function
      - name: Deploy count_update_calculator Lambda function
        run: |
          zip -r count_update.zip .
          aws lambda update-function-code \
            --function-name count_update_calculator \
            --zip-file fileb://count_update.zip

      # Step 5: Zip and deploy the Scan_and_sum_Dynamo1 Lambda function
      - name: Deploy Scan_and_sum_Dynamo1 Lambda function
        run: |
          zip -r scan_sum_function.zip .
          aws lambda update-function-code \
            --function-name Scan_and_sum_Dynamo1 \
            --zip-file fileb://scan_sum_function.zip
            
      - name: Debug Environment Variables
        run: env | sort
