name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
          
      # Step 3: Zip and deploy CalculatorTest Lambda function
      - name: Deploy CalculatorTest Lambda function
        run: |
          cd lambda-functions/calculator  # Navigate to the calculator directory
          zip -r ../calculator.zip .      # Zip only the contents, excluding the directory itself
          aws lambda update-function-code \
            --function-name CalculatorTest \
            --zip-file fileb://../calculator.zip  # Go back up one level to access the zip

      # Step 4: Zip and deploy count_update_calculator Lambda function
      - name: Deploy count_update_calculator Lambda function
        run: |
          cd lambda-functions/count-update  # Navigate to count-update directory
          zip -r ../count_update.zip .      # Zip only the contents, excluding the directory itself
          aws lambda update-function-code \
            --function-name count_update_calculator \
            --zip-file fileb://../count_update.zip

      # Step 5: Zip and deploy Scan_and_sum_Dynamo1 Lambda function
      - name: Deploy Scan_and_sum_Dynamo1 Lambda function
        run: |
          cd lambda-functions/scan-sum       # Navigate to scan-sum directory
          zip -r ../Scan_and_sum_Dynamo1.zip .  # Zip only the contents, excluding the directory itself
          aws lambda update-function-code \
            --function-name Scan_and_sum_Dynamo1 \
            --zip-file fileb://../Scan_and_sum_Dynamo1.zip
